custom: "https://www.paypal.me/isaiahodhner"
#                                          #
#                  |\                      #
#                  | \                     #
#                  |  \                    #
#                  |O O\                   #
#                  |__/ \                  #
#                  |    _\                 #
#                  |/\_\                   #
#                                          #
