import { defineConfig } from 'i18next-cli';

const availableLanguages = [
	// GENERATED by scripts/update-locales.js
	"ar", "ar-EG", "bn", "ceb", "cs", "da", "de", "el", "en", "es", "fa", "fi", "fr", "gu", "ha", "he", "hi", "hu", "id", "it", "ja", "jv", "ko", "mr", "nl", "pa", "pl", "pt", "ru", "sv", "sw", "ta", "te", "th", "tl", "tr", "uk", "ur", "vi", "zh"
	// END GENERATED
];

export default defineConfig({
	locales: availableLanguages,
	extract: {
		input: "{core,desktop-app}/**/*.{js,jsx,ts,tsx}",
		ignore: [
			"**/node_modules/**",
			"**/lib/**",
			"**/out/**",
			"**/dist/**",
			"**/build/**",
			"**/private/**",
			"**/electron-main.js", // uses top-level return
		],
		output: "core/locales/{{language}}/{{namespace}}.json",
		primaryLanguage: "en",
		nsSeparator: false,
		keySeparator: false,
	},
});