import { defineConfig } from 'i18next-cli';

const availableLanguages = [
	// GENERATED by scripts/update-locales.js
	"ar", "bn", "de", "en", "es", "fr", "ha", "hi", "id", "it", "ja", "ko", "mr", "nl", "pa", "pt", "ru", "sw", "te", "tl", "tr", "ur", "vi", "zh"
	// END GENERATED
];

export default defineConfig({
	locales: availableLanguages,
	extract: {
		input: "{core,desktop-app}/**/*.{js,jsx,ts,tsx}",
		ignore: [
			"**/node_modules/**",
			"**/lib/**",
			"**/out/**",
			"**/dist/**",
			"**/build/**",
			"**/private/**",
			"**/electron-main.js", // uses top-level return
		],
		output: "core/locales/{{language}}/{{namespace}}.json",
		primaryLanguage: "en",
		nsSeparator: false,
		keySeparator: false,
	},
});