import { defineConfig } from 'i18next-cli';

const availableLanguages = [
	// GENERATED by scripts/update-locales.js
	"de", "en", "es", "fr", "it", "nl"
	// END GENERATED
];

export default defineConfig({
	locales: availableLanguages,
	extract: {
		input: "{core,desktop-app}/**/*.{js,jsx,ts,tsx}",
		ignore: [
			"**/node_modules/**",
			"**/lib/**",
			"**/out/**",
			"**/dist/**",
			"**/build/**",
			"**/private/**",
			"**/electron-main.js", // uses top-level return
		],
		output: "core/locales/{{language}}/{{namespace}}.json",
		nsSeparator: false,
		keySeparator: false,
	},
});