
const fs = require("fs");
const path = require("path");

const localesFolder = path.join(__dirname, "..", "core", "locales");
const filePathsToUpdate = [
	path.join(__dirname, "..", "i18next.config.ts"),
	path.join(__dirname, "..", "core", "tracky-mouse.js"),
];

const markerStart = "// GENERATED by scripts/update-locales.js";
const markerEnd = "// END GENERATED";

const availableLanguages = fs.readdirSync(localesFolder).filter((name) => {
	return fs.existsSync(path.join(localesFolder, name, "translation.json"));
});
availableLanguages.sort((a, b) => a.localeCompare(b));

function updateFile(filePath) {
	const content = fs.readFileSync(filePath, "utf-8");
	const lines = content.split("\n");

	const startIndex = lines.findIndex(line => line.includes(markerStart));
	const endIndex = lines.findIndex(line => line.includes(markerEnd));
	if (startIndex === -1 || endIndex === -1 || startIndex >= endIndex) {
		throw new Error(`Markers not found or in wrong order in ${filePath}`);
	}

	const indent = lines[startIndex].match(/^(\s*)/)[1];
	const newLines = [
		...lines.slice(0, startIndex + 1),
		indent + availableLanguages.map(lang => JSON.stringify(lang)).join(", "),
		...lines.slice(endIndex)
	];
	const newContent = newLines.join("\n");
	const oldContent = lines.join("\n"); // instead of `content` for newline normalization
	if (newContent === oldContent) {
		console.log(`No changes needed for ${filePath}`);
		return;
	}
	fs.writeFileSync(filePath, newContent, "utf-8");
	console.log(`Updated ${filePath} with languages: ${availableLanguages.join(", ")}`);
}

for (const filePath of filePathsToUpdate) {
	updateFile(filePath);
}
